In [1]:
from excellib import set_excel_color_daily
from stocklib import get_stock_price, get_OTC_price, get_otc, get_investor, get_ratio
from stocklib import cal_bar, cal_KD, check_10days, check_10days_otc, get_trust_today
from stocklib import convert_num
from stock_plot import plot_K_chart

from finance import get_yearly, get_df_monthly, get_df_monthly_check, get_df_quarterly, get_df_quarterly_ori
from finance import get_this_quarter, get_quarter_income, get_quarter_finance, set_growth_eps
from finance import get_df_quarterly_all, get_df_yearly_all, get_df_yearly
from finance import get_df_quarterly_equity, get_finance_col, get_estimate_income
from finance import check_5_years

In [2]:
import requests
import shutil
import time
from datetime import date, timedelta, datetime
from dateutil.relativedelta import relativedelta
from bs4 import BeautifulSoup
from fake_useragent import UserAgent
import pandas as pd
import numpy as np
import yfinance as yf
import json
import matplotlib.pyplot as plt
import mplfinance as mpf
import seaborn as sns
from tqdm import tqdm
%matplotlib inline

ua = UserAgent()
root = '../'

root = 'D:/Mia/Stock/'
path_quarterly = root + 'quarterly/'
path_monthly = root + 'monthly/'
path_month_finance = root + 'monthly_finance/'
path_yearly = root + 'yearly/'
path_finance = root + 'finance/'
path_trust = root + 'trust/'
folder_name = 'trust/'

In [3]:
d_today = date.today() #- timedelta(days=1)

today_tw = d_today - relativedelta(years=1911)
this_year = d_today.year
this_quarter = get_this_quarter()
n = 1
if d_today.weekday() == 0:
    n = 3
d_yesterday = d_today - timedelta(days=n)
s_yesterday = (d_today - timedelta(days=n)).strftime("%Y%m%d")
s_today_md = (d_today).strftime("%m/%d")
s_yesterday_md = (d_today - timedelta(days=n)).strftime("%m/%d")
s_today = d_today.strftime("%Y%m%d")

s_today_tw = today_tw.strftime("%Y/%m/%d").lstrip('0')
s_thismonth_tw = today_tw.strftime("%Y/%m").lstrip('0')
print('今天:', d_today)
# 台灣證券交易所

今天: 2022-01-05

In [4]:
df_today = get_stock_price(d_today)
df_today.head(2)

取得今日上市股票資訊: 20220105

         name  amount    open    high    low  close
id
0050   元大台灣50   11730  150.10  150.55  149.1  149.3
0051  元大中型100      78   60.85   60.90   60.5   60.8

In [5]:
def get_EPS(lst_stock_id, filename):
    df_yearly_all = get_df_yearly_all() # 寫入歷年EPS、本益比，估算今年股價min, max範圍
    df_quarterly_all = get_df_quarterly_all()
    df_estimate = pd.DataFrame(columns = list(df_quarterly_all.columns)+['普通股數'])

    # 取得公司發行股數
    path_company_stock_num = root + 'company_list.xlsx'
    df_company_stock_num = pd.read_excel(path_company_stock_num, engine='openpyxl', dtype={'stock_id':str})
    df_company_stock_num.set_index('stock_id', inplace=True)
    
    lst_eps = []
    for i in tqdm(range(len(lst_stock_id))):
        stock_id = lst_stock_id[i]
        t_wait = np.random.randint(5,15)
        print(stock_id, ', wait ', t_wait)
        df = get_df_quarterly(stock_id)

        if df is None:
            print('df is None')
            continue
        if df.loc[df.index[0], '毛利率(%)'] < 20:
            print(stock_id, '：毛利率', df.loc[df.index[0], '毛利率(%)'], '< 20%，跳過')
            continue
        elif df.loc[df.index[0], '營益率(%)'] < 8:
            print(stock_id, '：營益率' , df.loc[df.index[0], '營益率(%)'] , ' < 8%，跳過')
            continue

        lst_eps.append(stock_id)
        # 計算歷年同季的營收成長率、EPS
        df = set_growth_eps(df, df_today, stock_id)

        # 將年度EPS寫到歷年excel裡
        lst_year = set(df.index.to_series().apply(lambda x:x[:4]))
        min_year = int(min(lst_year)) # 若最小年是2018 ，只能確定2019都有資料
        lst_year = [y for y in lst_year if int(y) > min_year]
        lst_EPS = [{'year':y, 'eps': df.loc[str(y)+'Q1', 'EPS(Y)']} for y in lst_year]

        df.reset_index(inplace=True)
        df = df.rename(columns={'index':'quarter'}) # reset_index後column名稱是index

        stock_name = ""
        if stock_id in df_today.index:
            stock_name = df_today.loc[stock_id, 'name']
            df_yearly = get_yearly(stock_id, lst_EPS, df['quarter'][0][:4], stock_name)    
            df_yearly_all = df_yearly_all.append(df_yearly, ignore_index=True)

        df.insert(0, 'name', value=stock_name)
        df.insert(0, 'stock_id', value=stock_id)

        df_quarterly_all = df_quarterly_all.append(df, ignore_index=True)
        time.sleep(t_wait)

        # ===============================
        # 預測EPS ( check_EPS )
        # ===============================
        df_new_quarter = get_quarter_finance(stock_id, df, this_year, this_quarter, df_company_stock_num, df_today)
        df_concat = pd.concat([df, df_new_quarter])
        df_concat.sort_values('quarter', ascending=False, inplace=True)
        df_estimate = df_estimate.append(df_concat)

    #預測EPS ( check_EPS )
    df_estimate.to_excel(path_check+'estimate_{}_{}.xlsx'.format(filename, s_today), index=False)
    return lst_eps

In [6]:
path_check = path_quarterly

# # 月報
# #### 彙總報表 (單位：千元)
# https://mops.twse.com.tw/mops/web/t21sc04_ifrs

# # 從月報 篩選出公司
# 上個月營收 > 30億
# 上個月營收成長 > 20% or 去年同季營收成長 > 20%
df_monthly_check = get_df_monthly_check(path_month_finance, income=30, income_growth_MoM=20, income_growth_YoY=20, pre_month=True)
df_monthly_check.head(2)

從月報 篩選出幾家公司
上個月營收 > 30億 上個月營收成長 > 20% or 去年同季營收成長 > 20%
(10534, 14)
目前月報年份： 110/11
所有公司筆數： 964
本月觀察公司筆數： 75

D:\Mia\Stock\code\finance.py:127: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_monthly_check['公司代號'] = df_monthly_check['公司代號'].astype(str)

,出表日期,資料年月,公司代號,公司名稱,產業別,營業收入-當月營收,營業收入-上月營收,營業收入-去年當月營收,營業收入-上月比較增減(%),營業收入-去年同月增減(%),累計營業收入-當月累計營收,累計營業收入-去年累計營收,累計營業收入-前期比較增減(%),備註
9594,110/11/08,110/9,1227,佳格,食品工業,32.95,28.14,39.59,17.09,-16.77,243.43,242.25,0.49,-
8637,110/10/11,110/8,1227,佳格,食品工業,28.14,25.58,31.67,9.99,-11.16,210.49,202.66,3.86,-

In [7]:
lst_monthly_id = list(df_monthly_check['公司代號'].unique())
if '6770' in lst_monthly_id:
    lst_monthly_id.remove('6770')
print(lst_monthly_id)

['1227', '1301', '1303', '1304', '1313', '1326', '1409', '1476', '1605', '1718', '1909', '2002', '2006', '2014', '2015', '2023', '2027', '2104', '2303', '2331', '2337', '2344', '2357', '2376', '2377', '2383', '2385', '2395', '2408', '2439', '2449', '2454', '2542', '2548', '2603', '2609', '2610', '2615', '2618', '2636', '2823', '2880', '2882', '2883', '2884', '2885', '2886', '2887', '2888', '2891', '3034', '3036', '3037', '3045', '3189', '3673', '3702', '3703', '3706', '5388', '5434', '5871', '6196', '6269', '6278', '6412', '6414', '6505', '6669', '8046', '8112', '8454', '9907', '9910']

In [8]:
lst_monthly_id = ['3023', '9914', '5306']

In [24]:
from fake_useragent import UserAgent
stock_id = '2330'
year=2018
season=3
ua = UserAgent()
agent = ua.random
url = 'https://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID={}&SYEAR={}&SSEASON={}&REPORT_ID=C'.format(stock_id, year, season)

headers = {'user-agent':agent}
res = requests.get(url, headers=headers)
res.encoding = 'big5'
soup = BeautifulSoup(res.text, 'lxml')
tables = soup.find_all('table')
df = pd.read_html(str(tables[0]))[0]
if len(df) < 10:
    df = pd.read_html(str(tables[1]))[0]

col_index = 0
    for i in range(len(df.columns)):
        if type(df.iloc[0,i]) == str:
            if '資產' in df.iloc[0,i]:
                col_index = i
df = df.set_index(df.columns[col_index])
print(col_index)
df

0

                            2018年09月30日   2017年12月31日   2017年09月30日
                                  資產負債表         資產負債表         資產負債表
(會計項目, 資產負債表)
資產                                  NaN           NaN           NaN
流動資產                                NaN           NaN           NaN
現金及約當現金                    4.887321e+08  5.533917e+08  4.080777e+08
透過損益按公允價值衡量之金融資產－流動        4.057240e+06  5.697510e+05  1.125668e+06
透過其他綜合損益按公允價值衡量之金融資產－流動    9.921407e+07  0.000000e+00  0.000000e+00
...                                 ...           ...           ...
非控制權益                      6.580870e+05  7.021100e+05  6.958420e+05
權益總計                       1.575830e+09  1.522760e+09  1.431413e+09
負債及權益總計                    1.969889e+09  1.991862e+09  1.841424e+09
預收股款（權益項下）之約當發行股數          0.000000e+00  0.000000e+00  0.000000e+00
母公司暨子公司所持有之母公司庫藏股股數（單位：股）  0.000000e+00  0.000000e+00  0.000000e+00

[91 rows x 3 columns]

In [3]:
df = get_df_quarterly_equity("2330")
df

c:\users\mia\appdata\local\programs\python\python37\lib\site-packages\openpyxl\styles\stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

get_equity： 2330 2021 3
get_equity： 2330 2021 2
get_equity： 2330 2021 1
get_equity： 2330 2020 4
get_equity： 2330 2020 3
get_equity： 2330 2020 2
get_equity： 2330 2020 1
get_equity： 2330 2019 4
get_equity： 2330 2019 3
get_equity： 2330 2019 2
get_equity： 2330 2019 1
get_equity： 2330 2018 4
get_equity： 2330 2018 3
get_equity： 2330 2018 2
get_equity： 2330 2018 1
get_equity： 2330 2017 4
get_equity： 2330 2017 3
get_equity： 2330 2017 2
get_equity： 2330 2017 1
get_equity： 2330 2016 4

科目(億),year,營業收入,營業成本,營業毛利,營業毛利(毛損)淨額,營業費用,營業利益,稅前淨利,所得稅費用,歸屬母公司淨利(損),每股盈餘(元),股東權益
2021Q3,2021,4146.70,2018.22,2128.49,2127.46,416.50,1710.04,1738.52,173.72,1562.58,6.02,20783
2021Q2,2021,3721.45,1859.11,1862.34,1861.97,405.83,1456.67,1493.91,149.09,1343.59,5.18,19939
2021Q1,2021,3624.10,1726.35,1897.75,1898.39,391.12,1505.38,1550.64,153.26,1396.90,5.39,19409
2020Q4,2020,3615.33,1663.44,1951.89,1952.36,383.21,1571.20,1611.07,182.83,1427.66,5.50,18506
2020Q3,2020,3564.26,1659.46,1904.81,1904.93,408.91,1500.47,1551.24,177.46,1373.10,5.30,17882
2020Q2,2020,3106.98,1460.06,1646.93,1646.24,335.21,1310.95,1363.99,155.06,1208.22,4.66,17212
2020Q1,2020,3105.97,1498.13,1607.84,1607.77,323.23,1285.22,1321.47,150.84,1169.87,4.51,16770
2019Q4,2019,3172.37,1579.96,1592.41,1592.02,349.43,1242.44,1287.82,127.04,1160.35,4.48,16220
2019Q3,2019,2930.45,1536.13,1394.32,1394.12,313.79,1078.87,1123.36,112.34,1010.70,3.90,15874
2019Q2,2019,2409.98,1373.25,1036.73,1037.30,271.65,763.04,805.45,137.70,667.65,2.57,15544
2019Q1,2019,2187.04,1283.52,903.52,903.58,260.18,642.66,681.82,67.94,613.94,2.37,17435
2018Q4,2018,2897.70,1517.28,1380.42,1381.19,308.52,1071.23,1110.82,110.77,999.84,3.85,16774
2018Q3,2018,2603.48,1369.67,1233.81,1233.67,281.28,952.45,988.97,97.99,890.72,3.44,15758
2018Q2,2018,2332.77,1216.89,1115.88,1115.31,264.40,844.28,875.88,152.94,722.91,2.79,14906
2018Q1,2018,2480.79,1231.04,1249.75,1248.58,267.28,968.27,999.44,101.56,897.85,3.46,16066
2017Q4,2017,2775.70,1388.55,1387.15,1387.48,288.42,1088.95,1116.75,123.69,992.86,3.83,15227
2017Q3,2017,2521.07,1262.31,1258.77,1258.80,275.37,980.56,1005.18,105.69,899.25,3.46,14314
2017Q2,2017,2138.55,1051.02,1087.53,1087.09,253.67,832.55,861.17,198.47,662.71,2.56,13423
2017Q1,2017,2339.14,1124.29,1214.86,1214.90,261.56,953.52,978.22,102.02,876.29,3.38,14563
2016Q4,2016,2622.27,1251.17,1371.10,1371.09,271.77,1099.07,1120.47,118.19,1002.00,3.86,13900
2016Q3,2016,2604.06,1283.67,1320.39,1320.51,258.41,1062.62,1082.50,114.61,967.59,3.74,0
2016Q2,2016,2218.10,1074.69,1143.41,1143.34,230.08,913.21,934.06,208.78,725.06,2.79,0
2016Q1,2016,2034.95,1121.25,913.70,913.38,208.79,704.67,722.56,74.63,647.81,2.50,0
2015Q4,2015,2035.19,1046.08,989.11,989.25,212.13,779.64,806.44,78.02,728.37,2.81,0
2015Q3,2015,2125.05,1101.88,1023.16,1023.36,221.60,783.89,833.95,80.77,753.29,2.90,0
2015Q2,2015,2054.40,1057.36,997.04,997.05,225.55,770.69,981.32,187.19,794.18,3.06,0
2015Q1,2015,2220.34,1125.85,1094.49,1094.29,225.39,866.26,882.59,92.75,789.90,3.05,0
2014Q4,2014,2225.21,1119.73,1105.48,1105.63,215.75,882.22,893.16,93.46,799.91,3.09,0

In [16]:
def check_5_years(stock_id):
    df_y = get_df_yearly(stock_id)
    df_y = df_y.apply(lambda x : round(x,1))
    if not 'cash' in df_y.columns:
        df_y['cash'] = 0
    if not '' in df_y.columns:
        df_y['現金股利_成長(%)'] = 0
        
    lst_check = ['營業收入','營業收入_成長(%)', '稅後淨利','稅後淨利_成長(%)', \
                 '毛利率(%)','毛利率_成長(%)', '營益率(%)', '淨利率(%)', '每股盈餘(元)', 'cash','現金股利_成長(%)']
    df_y = df_y.sort_index()[lst_check].T
    df_y.insert(0, 'stock_id', value=stock_id)
    df_y = df_y.dropna(axis=1)
#     df_5 = df_y[1:5]
#     if len(df_5[(df_5['營業收入_成長(%)']<-0.1)])>0:
#         print('營業收入_成長(%)<-0.1')
#     elif len(df_5[(df_5['稅後淨利_成長(%)']<-0.1)])>0:
#         print('稅後淨利_成長(%)<-0.1')
#     elif len(df_5[(df_5['每股盈餘_成長(%)']<-0.1)])>0:
#         print('每股盈餘_成長(%)<-0.1')
#     elif len(df_5[(df_5['毛利率_成長(%)']<-0.1)])>0:
#         print('毛利率_成長(%)<-0.1')
#     elif len(df_5[(df_5['現金股利_成長(%)']<-0.1)])>0:
#         print('現金股利_成長(%)<-0.1')
    return df_y

In [17]:
# lst_check = ['營業收入','營業收入_成長(%)', '稅後淨利','稅後淨利_成長(%)', \
#              '毛利率(%)','毛利率_成長(%)', '營益率(%)', '淨利率(%)', '每股盈餘(元)', 'cash','現金股利_成長(%)']
# lst_income = ['營業收入','營業收入_成長(%)']
# lst_gross = ['毛利率(%)','毛利率_成長(%)']
# lst_profit = ['稅後淨利','稅後淨利_成長(%)']
# lst_cash = ['cash','現金股利_成長(%)']

# a = df_y.sort_index()[lst_check].T
# a.insert(0, 'stock_id', value="2330")
# a.to_excel('test.xlsx')
# a

In [18]:
df_y_all = pd.DataFrame()

for stock_id in tqdm(lst_monthly_id):
    path_equity = root + 'equity/yearly_equity_{}.xlsx'.format(stock_id)
    t_wait = np.random.randint(5,10)
    print(stock_id, ', wait ', t_wait)
    df_y = check_5_years(stock_id)
    df_y_all = df_y_all.append(df_y)
        
    df_y.to_excel(path_equity)
    time.sleep(t_wait)

df_y_all.to_excel(path_check+'finance_{}.xlsx'.format(s_today))
df_y_all.head()

  0%|                                                                                            | 0/3 [00:00<?, ?it/s]

3023 , wait  8

 33%|████████████████████████████                                                        | 1/3 [00:08<00:17,  8.82s/it]

9914 , wait  9

 67%|████████████████████████████████████████████████████████                            | 2/3 [00:18<00:09,  9.33s/it]

5306 , wait  6
上櫃公司

100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:25<00:00,  8.42s/it]

,營業收入,營業收入_成長(%),稅後淨利,稅後淨利_成長(%),毛利率(%),毛利率_成長(%),營益率(%),淨利率(%),每股盈餘(元),cash,現金股利_成長(%),stock_id,2015,2016,2017,2018,2019,2020,2021,2014
營業收入,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3023,121.1,129.3,130.6,156.5,178.9,218.0,190.6,NaN
營業收入_成長(%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3023,NaN,0.1,0.0,0.2,0.1,0.2,-0.1,NaN
稅後淨利,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3023,9.6,11.7,12.3,13.6,16.7,21.8,20.1,NaN
稅後淨利_成長(%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3023,NaN,0.2,0.1,0.1,0.2,0.3,-0.1,NaN
毛利率(%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3023,22.5,24.8,25.1,25.1,25.7,25.6,25.8,NaN

In [ ]:
# # ==============================
# #  取得觀察中公司的季報、預測EPS
# # ==============================
# df_quarterly_all = get_df_quarterly_all()
# df_yearly_all = get_df_yearly_all() # 寫入歷年EPS、本益比，估算今年股價min, max範圍

# print('觀察中公司有：', len(lst_monthly_id), '筆')
# lst_monthly_id = get_EPS(lst_monthly_id, 'quarterly')
# print('EPS檢查', len(lst_monthly_id), '筆\n', lst_monthly_id)

In [109]:
# def get_equity(stock_id, year, season):
#     print(stock_id, year, season)
#     import requests
#     from bs4 import BeautifulSoup
#     from fake_useragent import UserAgent
#     ua = UserAgent()
#     agent = ua.random
#     url = 'https://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID={}&SYEAR={}&SSEASON={}&REPORT_ID=C'.format(stock_id, year, season)

#     headers = {'user-agent':agent}
#     res = requests.get(url, headers=headers)
#     res.encoding = 'big5'
#     soup = BeautifulSoup(res.text, 'lxml')
#     tables = soup.find_all('table')
#     df = pd.read_html(str(tables[0]))[0]
                                      
#     df = df.set_index(df.columns[1])
#     # 權益總計 Total equity、權益總額 Total equity
#     equity = float(df[df.index.str.contains("Total equity")].iloc[-1,1]) / 100000 # 千元>億
#     return equity

NameError: name 'this_year' is not defined